[[language]]
name = "twig"
language-servers = ["twiggy-language-server", "emmet-ls", "tailwindcss-language-server"]
file-types = ["twig"]
roots = ["templates"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls"]

[[language]]
name = "php"
formatter = { command = "php-cs-fixer-wrapper", args = ["/Users/bradley/work_projects/inscyte-crm"] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["--indent", "4"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

# LSPs

[language-server.twiggy-language-server]
command = "twiggy-language-server"
args = ["--stdio"]

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.biome]
command =  "biome" 
args = ["lsp-proxy"]

# Allow `!php/const` in yaml files without the LSP crying
[language-server.yaml-language-server.config]
yaml.customTags = ["!php/const scalar"]

