[[language]]
name = "twig"
language-servers = ["twiggy-language-server", "emmet-ls", "tailwindcss-language-server"]
file-types = ["twig"]
roots = ["templates"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls"]

[[language]]
name = "php"
formatter = { command = "php-cs-fixer-wrapper", args = ["%{working_directory}"] }
auto-format = true

[language-server.twiggy-language-server]
command = "twiggy-language-server"
args = ["--stdio"]

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.tailwindcss-language-server]
command = "tailwind-language-server"
args = ["--stdio"]
