[theme]
name = "catppuccin-mocha"

[keys]
prefix = "ctrl+s"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
reload_config = "prefix+comma"

[ui]
prompt_new_tab_name = false

[ui.sidebar.agents]
rows = [["state_icon", "workspace", "tab"]]
row_gap = 1

[theme.custom]
surface_dim = "#313244" # Temp fix

